4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

# 1. Initializing an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initializing an allone array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll-Ones Array (4x2):\n", ones_array)

# 3. Returning a new array of given shape and type, filled with fill value. 7 for example
filled_array = np.full((3, 3), 7)
print("\nArray Filled with 7 (3x3):\n", filled_array)

# 4. Returning a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array (same shape as reference_array):\n", zeros_like_array)

# 5. Returning a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Array (same shape as reference_array):\n", ones_like_array)

# 6. Converting given list to NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty Array (2x2):
 [[4.96425419e-310 0.00000000e+000]
 [1.22777155e-259 6.01347002e-154]]

All-Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array (same shape as reference_array):
 [[0 0]
 [0 0]]

Ones Array (same shape as reference_array):
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [2]:
import numpy as np

# 1. Creating an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array ranging from 10 to 49:\n", array_range)

# 2. Creating a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Creating a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Creating a 10x10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 Random Matrix:\n", random_matrix)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Creating a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element as 1:\n", zero_array)

# 7. Reversing an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed Array:\n", reversed_array)

# 8. Creating a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:\n", border_array)

# 9. Creating an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.52960761 0.19418709 0.02530701 0.74509745 0.20217652 0.65768829
 0.75614715 0.53231126 0.0068207  0.3751123  0.4842831  0.03244612
 0.55274776 0.42876066 0.51132761 0.25783261 0.25964993 0.50836354
 0.86756947 0.69704241 0.91677487 0.71331516 0.32431188 0.62681449
 0.61385897 0.20873229 0.73551535 0.35091984 0.55009866 0.33617091]
Mean of the array: 0.466699700179774

10x10 Random Matrix:
 [[0.46789602 0.64433465 0.42700708 0.03721838 0.39101906 0.87646781
  0.74725057 0.38058643 0.40012942 0.73808335]
 [0.04341277 0.29085735 0.8335739  0.42907793 0.38851923 0.26474857
  0.16290645 0.59827979 0.16940059 0.68717916]
 [0.35084774 0.16202593 0.43894989 0.36899627 0.17026409 0.78472269


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Adding the two arrays
addition = x + y
print("Addition of x and y:\n", addition)

# 2. Subtracting the two arrays
subtraction = x - y
print("\nSubtraction of x and y:\n", subtraction)

# 3. Multiplying the array with an integer
scaled_x = x * 3
print("\nMultiplication of x with 3:\n", scaled_x)

# 4. Finding the square of each element of the array
squared_x = np.square(x)
print("\nSquare of each element in x:\n", squared_x)

# 5. Find the dot product:
dot_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenating x and y along rows and v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nConcatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

# 7. Concatenating x and v; observe the error
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError in concatenating x and v:", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [4]:
import numpy as np

# Given Matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A.A⁻¹ = I:\n", identity_matrix)

# Round to eliminate numerical precision errors
identity_matrix_rounded = np.round(identity_matrix, decimals=10)
print("\nRounded Identity Matrix:\n", identity_matrix_rounded)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ == BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))

A.A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Rounded Identity Matrix:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ == BᵀAᵀ: True


4.2  Experiment: How Fast is Numpy? In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

  Element-wise Addition: • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation. • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [5]:
import numpy as np
import time

# Helper function to measure execution time
def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

# 1. Element-wise Addition
# Python lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

def python_addition(a, b):
    return [a[i] + b[i] for i in range(len(a))]

_, python_add_time = measure_time(python_addition, list1, list2)
print(f"Python List Addition Time: {python_add_time:.5f} seconds")

# NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

def numpy_addition(a, b):
    return a + b

_, numpy_add_time = measure_time(numpy_addition, array1, array2)
print(f"NumPy Array Addition Time: {numpy_add_time:.5f} seconds")

Python List Addition Time: 0.14103 seconds
NumPy Array Addition Time: 0.00723 seconds


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea- sure and Print the time taken for this operation.

  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [6]:
import numpy as np
import time

def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Python list multiplication
def python_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, python_mul_time = measure_time(python_multiplication, list1, list2)
print(f"Python List Multiplication Time: {python_mul_time:.5f} seconds")

# NumPy array multiplication
def numpy_multiplication(a, b):
    return a * b

_, numpy_mul_time = measure_time(numpy_multiplication, array1, array2)
print(f"NumPy Array Multiplication Time: {numpy_mul_time:.5f} seconds")

Python List Multiplication Time: 0.14990 seconds
NumPy Array Multiplication Time: 0.00492 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation. • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [7]:
import numpy as np
import time
def python_dot_product(a, b):
    return sum(a[i] * b[i] for i in range(len(a)))

_, python_dot_time = measure_time(python_dot_product, list1, list2)
print(f"Python List Dot Product Time: {python_dot_time:.5f} seconds")

# NumPy arrays
def numpy_dot_product(a, b):
    return np.dot(a, b)

_, numpy_dot_time = measure_time(numpy_dot_product, array1, array2)
print(f"NumPy Array Dot Product Time: {numpy_dot_time:.5f} seconds")

Python List Dot Product Time: 0.14835 seconds
NumPy Array Dot Product Time: 0.00193 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.

In [8]:
import numpy as np
import time

def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    end = time.time()
    return result, end - start

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Python list multiplication
def python_multiplication(a, b):
    return [a[i] * b[i] for i in range(len(a))]

_, python_mul_time = measure_time(python_multiplication, list1, list2)
print(f"Python List Multiplication Time: {python_mul_time:.5f} seconds")

# NumPy array multiplication
def numpy_multiplication(a, b):
    return a * b

_, numpy_mul_time = measure_time(numpy_multiplication, array1, array2)
print(f"NumPy Array Multiplication Time: {numpy_mul_time:.5f} seconds")

Python List Multiplication Time: 0.15934 seconds
NumPy Array Multiplication Time: 0.00259 seconds
